site_name: ""

repo_name: bisonai/datamaxi-python
repo_url: https://github.com/bisonai/datamaxi-python

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            separate_signature: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            merge_init_into_class: true
            members_order: source

markdown_extensions:
  - toc:
      permalink: true
  - codehilite
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences

nav:
  - Main: index.md
  - API: api.md
  - Datamaxi:
      - Candle: candle.md
      - Funding Rate: funding-rate.md
  - Defillama: defillama.md
  - Trend:
      - Naver Trend: naver-trend.md
      - Google Trend: google-trend.md

theme:
  name: material
  logo: /assets/logo.png
  favicon: /assets/images/favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.path

watch:
  - datamaxi

extra_css: [extra.css]

extra:
  homepage:
  analytics:
    provider: google
    property: G-X2HTG9B39J
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Bisonai
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/datamaxiplus
    - icon: fontawesome/brands/telegram
      link: https://t.me/datamaxiplus
    - icon: fontawesome/brands/medium
      link: https://medium.com/@datamaxiplus

copyright: Copyright &copy; 2024 DataMaxi+
