site_name: ""

repo_name: bisonai/datamaxi-python
repo_url: https://github.com/bisonai/datamaxi-python

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            separate_signature: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            merge_init_into_class: true

markdown_extensions:
  - toc:
      permalink: true
  - codehilite
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences

nav:
  - Main: index.md
  - API: api.md
  - CEX:
      - Binance: binance.md
      - Bithumb: bithumb.md
      - Bybit: bybit.md
      - Coinone: coinone.md
      - Huobi: huobi.md
      - Okx: okx.md
      - Upbit: upbit.md
  - Defillama: defillama.md
  - Trend:
      - Naver Trend: naver-trend.md
      - Google Trend: google-trend.md

theme:
  name: material
  logo: /assets/logo.png
  favicon: /assets/images/favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  features:
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.path

watch:
  - datamaxi

extra:
  homepage: https://datamaxiplus.com/
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Bisonai
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/datamaxiplus
    - icon: fontawesome/brands/telegram
      link: https://t.me/datamaxiplus
    - icon: fontawesome/brands/medium
      link: https://medium.com/@datamaxiplus

copyright: Copyright &copy; 2024 BISONAI PTE. LTD.
